/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import java.awt.Dimension;
import java.awt.Font;
import javax.swing.JOptionPane;

/**
 *
 * @author jenni
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
            initComponents();
            //Maximizando
               this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        lbldependencia1 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jp_menu = new javax.swing.JPanel();
        lblusuarios = new javax.swing.JLabel();
        lbllibros = new javax.swing.JLabel();
        lblasesor = new javax.swing.JLabel();
        lbldependencia = new javax.swing.JLabel();
        lblentrada = new javax.swing.JLabel();
        lbldetalleentrada = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        lbldetallesalida = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        lblsalida = new javax.swing.JLabel();
        escritorio = new javax.swing.JDesktopPane();
        Lblbiendenido = new javax.swing.JLabel();
        LblNombre = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        lbldependencia1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbldependencia1.setForeground(new java.awt.Color(255, 255, 255));
        lbldependencia1.setText("Dependencia");
        lbldependencia1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbldependencia1MouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jp_menu.setBackground(new java.awt.Color(51, 51, 51));
        jp_menu.setForeground(new java.awt.Color(255, 255, 255));

        lblusuarios.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblusuarios.setForeground(new java.awt.Color(255, 255, 255));
        lblusuarios.setText("USUARIOS");
        lblusuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblusuariosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblusuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblusuariosMouseExited(evt);
            }
        });

        lbllibros.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbllibros.setForeground(new java.awt.Color(255, 255, 255));
        lbllibros.setText("LIBRO");
        lbllibros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbllibrosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbllibrosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbllibrosMouseExited(evt);
            }
        });

        lblasesor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblasesor.setForeground(new java.awt.Color(255, 255, 255));
        lblasesor.setText("ASESOR");
        lblasesor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblasesorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblasesorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblasesorMouseExited(evt);
            }
        });

        lbldependencia.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbldependencia.setForeground(new java.awt.Color(255, 255, 255));
        lbldependencia.setText("DEPENDENCIA");
        lbldependencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbldependenciaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbldependenciaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbldependenciaMouseExited(evt);
            }
        });

        lblentrada.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblentrada.setForeground(new java.awt.Color(255, 255, 255));
        lblentrada.setText("ENTRADA");
        lblentrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblentradaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblentradaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblentradaMouseExited(evt);
            }
        });

        lbldetalleentrada.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbldetalleentrada.setForeground(new java.awt.Color(255, 255, 255));
        lbldetalleentrada.setText("DETALLE ENTRADA");
        lbldetalleentrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbldetalleentradaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbldetalleentradaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbldetalleentradaMouseExited(evt);
            }
        });

        lbldetallesalida.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbldetallesalida.setForeground(new java.awt.Color(255, 255, 255));
        lbldetallesalida.setText("DETALLE SALIDA");
        lbldetallesalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbldetallesalidaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbldetallesalidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbldetallesalidaMouseExited(evt);
            }
        });

        lblsalida.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblsalida.setForeground(new java.awt.Color(255, 255, 255));
        lblsalida.setText("SAlIDA");
        lblsalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblsalidaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblsalidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblsalidaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jp_menuLayout = new javax.swing.GroupLayout(jp_menu);
        jp_menu.setLayout(jp_menuLayout);
        jp_menuLayout.setHorizontalGroup(
            jp_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jp_menuLayout.createSequentialGroup()
                .addGroup(jp_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jp_menuLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(lblentrada))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jp_menuLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(lblusuarios))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jp_menuLayout.createSequentialGroup()
                .addGroup(jp_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jp_menuLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jp_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbldependencia)
                            .addGroup(jp_menuLayout.createSequentialGroup()
                                .addComponent(lblasesor)
                                .addGap(32, 32, 32))))
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jp_menuLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lbldetalleentrada))
                    .addGroup(jp_menuLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(lbldetallesalida))
                    .addGroup(jp_menuLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(lbllibros))
                    .addGroup(jp_menuLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(lblsalida))
                    .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_menuLayout.setVerticalGroup(
            jp_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_menuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblusuarios)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbllibros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(lblasesor)
                .addGroup(jp_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_menuLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(lbldependencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(lblentrada))
                    .addGroup(jp_menuLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbldetalleentrada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(lbldetallesalida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblsalida)
                .addContainerGap(276, Short.MAX_VALUE))
        );

        escritorio.setBackground(new java.awt.Color(51, 51, 51));

        Lblbiendenido.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Lblbiendenido.setForeground(new java.awt.Color(255, 255, 255));
        Lblbiendenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lblbiendenido.setText("BIENVENIDO");

        LblNombre.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LblNombre.setForeground(new java.awt.Color(255, 255, 255));
        LblNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblNombre.setText("NOMBRE");

        escritorio.setLayer(Lblbiendenido, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(LblNombre, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Lblbiendenido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
            .addComponent(LblNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(Lblbiendenido)
                .addGap(55, 55, 55)
                .addComponent(LblNombre)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jp_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(escritorio)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //Declarando objetos
    frmTodoUsuario frmttodousuario = new frmTodoUsuario();
     frmTodoLibro frmtodolibro = new frmTodoLibro();
     frmTodoAsesor frmtodoasesor = new frmTodoAsesor();
     frmTodoDependencia frmtododependencia = new frmTodoDependencia();
     frmTodoEntrada frmtodoentrada = new frmTodoEntrada();
     frmTodoDetalleEntrada frmtododetalleentrada= new frmTodoDetalleEntrada();
     frm_RegistroEntrada frmregistroentrada=new  frm_RegistroEntrada();
     frm_RegistroSalida frmregistrosalida=new frm_RegistroSalida();
     frmTodoSalida frmtodosalida=new frmTodoSalida();
     frmTodoDetalleSalida frmtododetallesalida=new frmTodoDetalleSalida();
     //DEclarar variables publicas
    public int  idUsuario;
    public String NombreUsuario;
    public String apellidoUsuario;
    public String telefono;
    public String correo;
    public String nick;
    public String contrasena;
    public String Rol;
    
    
    private void lblusuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblusuariosMouseClicked
       try {
        boolean mostrar=true;
        String Nombre=frmttodousuario.getTitle();
        for (int a=0;a<escritorio.getComponentCount();a++){     // verificar si es instancia de algun componente que ya este en el jdesktoppane
        if( frmttodousuario.getClass().isInstance( escritorio.getComponent(a) )){
        // JOptionPane.showMessageDialog(rootPane, "La ventana "+Nombre+" que interta abrir ya está abierta, cierre la ventana actual e intente nuevamente");
        System.out.println("esta instancia, no se debe mostrar");
        frmttodousuario.toFront();
        escritorio.moveToFront(frmttodousuario);
        mostrar=false;
     }else{
        System.out.println("no lo es, puede mostrarse");
    }
}
        if(mostrar){
        Dimension desktopSize = escritorio.getSize();
        frmttodousuario.setSize(escritorio.getSize());
        escritorio.add(frmttodousuario);
        ((javax.swing.plaf.basic.BasicInternalFrameUI)frmttodousuario.getUI()).setNorthPane(null);//Con esto quito el title
        }
         frmttodousuario.show();
        } catch (Exception e) {
          JOptionPane.showConfirmDialog(null,"Error: " + e);
        }
    }//GEN-LAST:event_lblusuariosMouseClicked

    private void lbllibrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllibrosMouseClicked
        try {
        boolean mostrar=true;
        String Nombre=frmtodolibro.getTitle();
        for (int a=0;a<escritorio.getComponentCount();a++){     // verificar si es instancia de algun componente que ya este en el jdesktoppane
        if( frmtodolibro.getClass().isInstance( escritorio.getComponent(a) )){
        // JOptionPane.showMessageDialog(rootPane, "La ventana "+Nombre+" que interta abrir ya está abierta, cierre la ventana actual e intente nuevamente");
        System.out.println("esta instancia, no se debe mostrar");
        frmtodolibro.toFront();
        escritorio.moveToFront(frmtodolibro);
        mostrar=false;
     }else{
        System.out.println("no lo es, puede mostrarse");
    }
}
        if(mostrar){
        Dimension desktopSize = escritorio.getSize();
        frmtodolibro.setSize(escritorio.getSize());
        escritorio.add(frmtodolibro);
        ((javax.swing.plaf.basic.BasicInternalFrameUI)frmtodolibro.getUI()).setNorthPane(null);//Con esto quito el title
        }
         frmtodolibro.show();
        } catch (Exception e) {
          JOptionPane.showConfirmDialog(null,"Error: " + e);
        }
    }//GEN-LAST:event_lbllibrosMouseClicked

    private void lblasesorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblasesorMouseClicked
       try {
        boolean mostrar=true;
        String Nombre=frmtodoasesor.getTitle();
        for (int a=0;a<escritorio.getComponentCount();a++){     // verificar si es instancia de algun componente que ya este en el jdesktoppane
        if( frmtodoasesor.getClass().isInstance( escritorio.getComponent(a) )){
        // JOptionPane.showMessageDialog(rootPane, "La ventana "+Nombre+" que interta abrir ya está abierta, cierre la ventana actual e intente nuevamente");
        System.out.println("esta instancia, no se debe mostrar");
        frmtodoasesor.toFront();
        escritorio.moveToFront(frmtodoasesor);
        mostrar=false;
     }else{
        System.out.println("no lo es, puede mostrarse");
    }
}
        if(mostrar){
        Dimension desktopSize = escritorio.getSize();
        frmtodolibro.setSize(escritorio.getSize());
        escritorio.add(frmtodoasesor);
        ((javax.swing.plaf.basic.BasicInternalFrameUI)frmtodoasesor.getUI()).setNorthPane(null);//Con esto quito el title
        }
         frmtodoasesor.show();
        } catch (Exception e) {
          JOptionPane.showConfirmDialog(null,"Error: " + e);
        }
    }//GEN-LAST:event_lblasesorMouseClicked

    private void lbldependenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldependenciaMouseClicked
       try {
        boolean mostrar=true;
        String Nombre=frmtododependencia.getTitle();
        for (int a=0;a<escritorio.getComponentCount();a++){     // verificar si es instancia de algun componente que ya este en el jdesktoppane
        if( frmtododependencia.getClass().isInstance( escritorio.getComponent(a) )){
        // JOptionPane.showMessageDialog(rootPane, "La ventana "+Nombre+" que interta abrir ya está abierta, cierre la ventana actual e intente nuevamente");
        System.out.println("esta instancia, no se debe mostrar");
        frmtododependencia.toFront();
        escritorio.moveToFront(frmtododependencia);
        mostrar=false;
     }else{
        System.out.println("no lo es, puede mostrarse");
    }
}
        if(mostrar){
        Dimension desktopSize = escritorio.getSize();
        frmtododependencia.setSize(escritorio.getSize());
        escritorio.add(frmtododependencia);
        ((javax.swing.plaf.basic.BasicInternalFrameUI)frmtododependencia.getUI()).setNorthPane(null);//Con esto quito el title
        }
         frmtododependencia.show();
        } catch (Exception e) {
          JOptionPane.showConfirmDialog(null,"Error: " + e);
        }
    }//GEN-LAST:event_lbldependenciaMouseClicked

    private void lbldependencia1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldependencia1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbldependencia1MouseClicked

    private void lblentradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblentradaMouseClicked
        // TODO add your handling code here:
        try {
        boolean mostrar=true;
        String Nombre=frmregistroentrada.getTitle();
        for (int a=0;a<escritorio.getComponentCount();a++){     // verificar si es instancia de algun componente que ya este en el jdesktoppane
        if( frmregistroentrada.getClass().isInstance( escritorio.getComponent(a) )){
        // JOptionPane.showMessageDialog(rootPane, "La ventana "+Nombre+" que interta abrir ya está abierta, cierre la ventana actual e intente nuevamente");
        System.out.println("esta instancia, no se debe mostrar");
        frmregistroentrada.toFront();
        escritorio.moveToFront(frmregistroentrada);
        mostrar=false;
     }else{
        System.out.println("no lo es, puede mostrarse");
    }
}
        if(mostrar){
        Dimension desktopSize = escritorio.getSize();
        frmregistroentrada.setSize(escritorio.getSize());
        escritorio.add(frmregistroentrada);
         frmregistroentrada.TxtNombreusuario.setText(NombreUsuario+" "+apellidoUsuario);
         frmregistroentrada.TxtidUsuario.setText(idUsuario+"");
        ((javax.swing.plaf.basic.BasicInternalFrameUI)frmregistroentrada.getUI()).setNorthPane(null);//Con esto quito el title
        }
         frmregistroentrada.show();
        } catch (Exception e) {
          JOptionPane.showConfirmDialog(null,"Error: " + e);
        }

    }//GEN-LAST:event_lblentradaMouseClicked

    private void lbldetalleentradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldetalleentradaMouseClicked
        // TODO add your handling code here:
         try {
        boolean mostrar=true;
        String Nombre=frmtododetalleentrada.getTitle();
        for (int a=0;a<escritorio.getComponentCount();a++){     // verificar si es instancia de algun componente que ya este en el jdesktoppane
        if( frmtododetalleentrada.getClass().isInstance( escritorio.getComponent(a) )){
        // JOptionPane.showMessageDialog(rootPane, "La ventana "+Nombre+" que interta abrir ya está abierta, cierre la ventana actual e intente nuevamente");
        System.out.println("esta instancia, no se debe mostrar");
        frmtododetalleentrada.toFront();
        escritorio.moveToFront(frmtododetalleentrada);
        mostrar=false;
     }else{
        System.out.println("no lo es, puede mostrarse");
    }
}
        if(mostrar){
        Dimension desktopSize = escritorio.getSize();
        frmtododetalleentrada.setSize(escritorio.getSize());
        escritorio.add(frmtododetalleentrada);
        ((javax.swing.plaf.basic.BasicInternalFrameUI)frmtododetalleentrada.getUI()).setNorthPane(null);//Con esto quito el title
        }
         frmtododetalleentrada.show();
        } catch (Exception e) {
          JOptionPane.showConfirmDialog(null,"Error: " + e);
        }
    }//GEN-LAST:event_lbldetalleentradaMouseClicked

    private void lblentradaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblentradaMouseEntered
        // TODO add your handling code here:
        Font fuenteactual=lblentrada.getFont();
        Font nuevafuente=fuenteactual.deriveFont(fuenteactual.getSize()+5F);
        lblentrada.setFont(nuevafuente);
    }//GEN-LAST:event_lblentradaMouseEntered

    private void lblusuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblusuariosMouseEntered
        // TODO add your handling code here:
        Font fuenteactual=lblusuarios.getFont();
        Font nuevafuente=fuenteactual.deriveFont(fuenteactual.getSize()+5F);
        lblusuarios.setFont(nuevafuente);
        
    }//GEN-LAST:event_lblusuariosMouseEntered

    private void lblusuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblusuariosMouseExited
        // TODO add your handling code here:
        Font fuenteactual=lblusuarios.getFont();
        Font nuevafuente=fuenteactual.deriveFont(fuenteactual.getSize()-5F);
        lblusuarios.setFont(nuevafuente);
    }//GEN-LAST:event_lblusuariosMouseExited

    private void lbllibrosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllibrosMouseEntered
        // TODO add your handling code here:
        Font fuenteactual=lbllibros.getFont();
        Font nuevafuente=fuenteactual.deriveFont(fuenteactual.getSize()+5F);
        lbllibros.setFont(nuevafuente);
    }//GEN-LAST:event_lbllibrosMouseEntered

    private void lbllibrosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllibrosMouseExited
        // TODO add your handling code here:
        Font fuenteactual=lbllibros.getFont();
        Font nuevafuente=fuenteactual.deriveFont(fuenteactual.getSize()-5F);
        lbllibros.setFont(nuevafuente);
    }//GEN-LAST:event_lbllibrosMouseExited

    private void lblasesorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblasesorMouseEntered
        // TODO add your handling code here:
        Font fuenteactual=lblasesor.getFont();
        Font nuevafuente=fuenteactual.deriveFont(fuenteactual.getSize()+5F);
        lblasesor.setFont(nuevafuente);
    }//GEN-LAST:event_lblasesorMouseEntered

    private void lblasesorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblasesorMouseExited
        // TODO add your handling code here:
        Font fuenteactual=lblasesor.getFont();
        Font nuevafuente=fuenteactual.deriveFont(fuenteactual.getSize()-5F);
        lblasesor.setFont(nuevafuente);
    }//GEN-LAST:event_lblasesorMouseExited

    private void lbldependenciaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldependenciaMouseEntered
        // TODO add your handling code here:
        Font fuenteactual=lbldependencia.getFont();
        Font nuevafuente=fuenteactual.deriveFont(fuenteactual.getSize()+5F);
        lbldependencia.setFont(nuevafuente);
    }//GEN-LAST:event_lbldependenciaMouseEntered

    private void lbldependenciaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldependenciaMouseExited
        // TODO add your handling code here:
        Font fuenteactual=lbldependencia.getFont();
        Font nuevafuente=fuenteactual.deriveFont(fuenteactual.getSize()-5F);
        lbldependencia.setFont(nuevafuente);
    }//GEN-LAST:event_lbldependenciaMouseExited

    private void lblentradaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblentradaMouseExited
        // TODO add your handling code here:
        Font fuenteactual=lblentrada.getFont();
        Font nuevafuente=fuenteactual.deriveFont(fuenteactual.getSize()-5F);
        lblentrada.setFont(nuevafuente);
    }//GEN-LAST:event_lblentradaMouseExited

    private void lblsalidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsalidaMouseClicked
        // TODO add your handling code here:
        try {
        boolean mostrar=true;
        String Nombre=frmtodosalida.getTitle();
        for (int a=0;a<escritorio.getComponentCount();a++){     // verificar si es instancia de algun componente que ya este en el jdesktoppane
        if( frmtodosalida.getClass().isInstance( escritorio.getComponent(a) )){
        // JOptionPane.showMessageDialog(rootPane, "La ventana "+Nombre+" que interta abrir ya está abierta, cierre la ventana actual e intente nuevamente");
        System.out.println("esta instancia, no se debe mostrar");
        frmtodosalida.toFront();
        escritorio.moveToFront(frmtodosalida);
        mostrar=false;
     }else{
        System.out.println("no lo es, puede mostrarse");
    }
}
        if(mostrar){
        Dimension desktopSize = escritorio.getSize();
        frmtodosalida.setSize(escritorio.getSize());
        escritorio.add(frmtodosalida);
       
        ((javax.swing.plaf.basic.BasicInternalFrameUI)frmtodosalida.getUI()).setNorthPane(null);//Con esto quito el title
        }
         frmtodosalida.show();
        } catch (Exception e) {
          JOptionPane.showConfirmDialog(null,"Error: " + e);
        }


    }//GEN-LAST:event_lblsalidaMouseClicked

    private void lbldetalleentradaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldetalleentradaMouseEntered
        // TODO add your handling code here:
        Font fuenteactual=lbldetalleentrada.getFont();
        Font nuevafuente=fuenteactual.deriveFont(fuenteactual.getSize()+5F);
        lbldetalleentrada.setFont(nuevafuente);
    }//GEN-LAST:event_lbldetalleentradaMouseEntered

    private void lbldetalleentradaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldetalleentradaMouseExited
        // TODO add your handling code here:
        Font fuenteactual=lbldetalleentrada.getFont();
        Font nuevafuente=fuenteactual.deriveFont(fuenteactual.getSize()-5F);
        lbldetalleentrada.setFont(nuevafuente);
    }//GEN-LAST:event_lbldetalleentradaMouseExited

    private void lbldetallesalidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldetallesalidaMouseEntered
        // TODO add your handling code here:
        Font fuenteactual=lbldetallesalida.getFont();
        Font nuevafuente=fuenteactual.deriveFont(fuenteactual.getSize()+5F);
        lbldetallesalida.setFont(nuevafuente);
    }//GEN-LAST:event_lbldetallesalidaMouseEntered

    private void lbldetallesalidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldetallesalidaMouseExited
        // TODO add your handling code here:
        Font fuenteactual=lbldetallesalida.getFont();
        Font nuevafuente=fuenteactual.deriveFont(fuenteactual.getSize()-5F);
        lbldetallesalida.setFont(nuevafuente);
    }//GEN-LAST:event_lbldetallesalidaMouseExited

    private void lblsalidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsalidaMouseEntered
        // TODO add your handling code here:
        Font fuenteactual=lblsalida.getFont();
        Font nuevafuente=fuenteactual.deriveFont(fuenteactual.getSize()+5F);
        lblsalida.setFont(nuevafuente);
    }//GEN-LAST:event_lblsalidaMouseEntered

    private void lblsalidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsalidaMouseExited
        // TODO add your handling code here:
        Font fuenteactual=lblsalida.getFont();
        Font nuevafuente=fuenteactual.deriveFont(fuenteactual.getSize()-5F);
        lblsalida.setFont(nuevafuente);
    }//GEN-LAST:event_lblsalidaMouseExited

    private void lbldetallesalidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldetallesalidaMouseClicked
        // TODO add your handling code here:
        try {
        boolean mostrar=true;
        String Nombre=frmtododetallesalida.getTitle();
        for (int a=0;a<escritorio.getComponentCount();a++){     // verificar si es instancia de algun componente que ya este en el jdesktoppane
        if( frmtododetallesalida.getClass().isInstance( escritorio.getComponent(a) )){
        // JOptionPane.showMessageDialog(rootPane, "La ventana "+Nombre+" que interta abrir ya está abierta, cierre la ventana actual e intente nuevamente");
        System.out.println("esta instancia, no se debe mostrar");
        frmtododetallesalida.toFront();
        escritorio.moveToFront(frmtododetallesalida);
        mostrar=false;
     }else{
        System.out.println("no lo es, puede mostrarse");
    }
}
        if(mostrar){
        Dimension desktopSize = escritorio.getSize();
        frmtododetallesalida.setSize(escritorio.getSize());
        escritorio.add(frmtododetallesalida);
       
        ((javax.swing.plaf.basic.BasicInternalFrameUI)frmtododetallesalida.getUI()).setNorthPane(null);//Con esto quito el title
        }
         frmtododetallesalida.show();
        } catch (Exception e) {
          JOptionPane.showConfirmDialog(null,"Error: " + e);
        }

    }//GEN-LAST:event_lbldetallesalidaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel LblNombre;
    private javax.swing.JLabel Lblbiendenido;
    public static javax.swing.JDesktopPane escritorio;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JPanel jp_menu;
    private javax.swing.JLabel lblasesor;
    private javax.swing.JLabel lbldependencia;
    private javax.swing.JLabel lbldependencia1;
    private javax.swing.JLabel lbldetalleentrada;
    private javax.swing.JLabel lbldetallesalida;
    private javax.swing.JLabel lblentrada;
    private javax.swing.JLabel lbllibros;
    private javax.swing.JLabel lblsalida;
    private javax.swing.JLabel lblusuarios;
    // End of variables declaration//GEN-END:variables
}
